version: "3"
services:
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - "9042:9042/tcp"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017/tcp"
  postgis:
    container_name: postgis
    environment:
      - POSTGRES_USER=mars
      - POSTGRES_PASSWORD=poly2021
    image: postgis/postgis
    ports:
      - "5432:5432/tcp"
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=mars
      - POSTGRES_PASSWORD=poly2021
    image: postgres
    ports:
      - "5433:5433/tcp"
    command: -p 5433
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379/tcp"
    working_dir: /data
  timescale:
    container_name: timescale
    environment:
      - POSTGRES_USER=mars
      - POSTGRES_PASSWORD=poly2021
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5431:5432/tcp"
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    #volumes:
    #  - minio_storage:/data
    environment:
      - MINIO_ROOT_USER=mars
      - MINIO_ROOT_PASSWORD=poly2021
    command: server --console-address ":9001" /data

#volumes:
#  minio_storage: {}