apiVersion: v1
kind: ConfigMap
metadata:
  name: soh-config
data:
  config.json: |
    {
      "simulation": {
        "iterations": 43200,
        "randomSeed": 42
      },
      "initialization": {
        "initializers": [
          {
            "name": "SemiTruckDriver",
            "file": "resources/semi_truck_initializer.csv",
            "count": 6500
          }
        ]
      },
      "outputs": [
        {
          "kind": "trips",
          "outputConfiguration": {
            "tripsFields": [
              "StableId",
              "StartPosition",
              "EndPosition",
              "DistanceTraveled",
              "Duration"
            ]
          }
        }
      ]
    }
