apiVersion: v1
kind: ConfigMap
metadata:
  name: soh-config
  namespace: wwr434-default
data:
  config.json: |
    {
      "simulation": {
        "iterations": 43200,
        "randomSeed": 42,
        "npgSqlOptions": {
          "port": "5432",
          "host": "postgres-service",
          "user": "mars_user",
          "password": "Password123+",
          "databaseName": "mars_user",
          "overrideByConflict": true
        }
      },    
      "initialization": {
        "initializers": [
          {
            "name": "SemiTruckDriver",
            "file": "resources/semi_truck_initializer.csv",
            "count": 6500
          }
        ]
      },
      "outputs": [
        {
          "kind": "postgres"
        }
      ]
    }
    