
apiVersion: v1
kind: Config
preferences: {}
clusters:
  - cluster:
      certificate-authority-data: "Your Certificate"
      server: https://icc-api.informatik.haw-hamburg.de:443
    name: icc
contexts:
  - context:
      cluster: icc
      namespace: Username-default
      user: Username
    name: icc
current-context: icc
users:
  - name: Username
    user:
      token: "Your Token"
      