apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soh-output-pvc
  namespace: wwr434-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block